version: "3.9"

services:
  app:
    build: .
    command: gunicorn urbvans.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
      - cache
    environment:
      - DEBUG=False
    expose:
      - 8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    restart: always

  db:
    image: postgres:alpine
    env_file:
      - app/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - static_volume:/home/staticfiles
    restart: always

  cache:
    image: memcached:alpine
    restart: always

volumes:
  postgres_data:
  static_volume:
